// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1210:Using directives should be ordered alphabetically by namespace", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1208:System using directives should be placed before other using directives", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1412:Store files as UTF-8 with byte order mark", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SX1309:Field names should begin with underscore", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.BotBuilderSamples.Controllers.BotController.Adapter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1306:Field names should begin with lower-case letter", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.BotBuilderSamples.Controllers.BotController.Adapter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SX1309:Field names should begin with underscore", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.BotBuilderSamples.Controllers.BotController.Bot")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1306:Field names should begin with lower-case letter", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.BotBuilderSamples.Controllers.BotController.Bot")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1507:Code should not contain multiple blank lines in a row", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Bots.SharePointBotDrivenAceActionBot.OnSharePointTaskGetPropertyPaneConfigurationAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IInvokeActivity},Microsoft.Bot.Schema.Teams.TaskModuleRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.Bot.Schema.SharePoint.GetPropertyPaneConfigurationResponse}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1003:Symbols should be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Helpers.CardHelper.CreateAdaptiveCardAttachment(Microsoft.Bot.Schema.Teams.MessagingExtensionAction,Microsoft.BotBuilderSamples.Models.CardResponse)~System.Collections.Generic.List{Microsoft.Bot.Schema.Teams.MessagingExtensionAttachment}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1137:Elements should have the same indentation", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Helpers.CardHelper.CreateAdaptiveCardAttachment(Microsoft.Bot.Schema.Teams.MessagingExtensionAction,Microsoft.BotBuilderSamples.Models.CardResponse)~System.Collections.Generic.List{Microsoft.Bot.Schema.Teams.MessagingExtensionAttachment}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1003:Symbols should be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Helpers.CardHelper.CreateAdaptiveCardAttachmentForHTML(Microsoft.Bot.Schema.Teams.MessagingExtensionAction,Microsoft.BotBuilderSamples.Models.CardResponse)~System.Collections.Generic.List{Microsoft.Bot.Schema.Teams.MessagingExtensionAttachment}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1137:Elements should have the same indentation", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Helpers.CardHelper.CreateAdaptiveCardAttachmentForHTML(Microsoft.Bot.Schema.Teams.MessagingExtensionAction,Microsoft.BotBuilderSamples.Models.CardResponse)~System.Collections.Generic.List{Microsoft.Bot.Schema.Teams.MessagingExtensionAttachment}")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1508:Closing braces should not be preceded by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.BotBuilderSamples.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CardResponse.Subtitle")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CardResponse.Text")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CardResponse.UserName")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CardResponse.UserPwd")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CustomFormResponse.EmpEmail")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.CustomFormResponse.EmpName")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.BotBuilderSamples.Models.RazorViewResponse.DisplayData")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.BotBuilderSamples.Models.CustomFormResponse")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.BotBuilderSamples.Models.RazorViewResponse")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "<Pending>", Scope = "type", Target = "~T:TeamsMessagingExtensionsAction.Pages.IndexModel")]
